server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url:  jdbc:h2:tcp://localhost/C:\study\h2\provisioning
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      open-in-view: false
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace